java_library(
    name = "intellij",
    srcs = glob(["*.java"]),
    deps = [
        "@maven//:cheshire_cheshire",
        "@maven//:lambdaisland_kaocha",
        "@maven//:org_clojure_clojure",
        "@maven//:org_clojure_core_specs_alpha",
        "@maven//:org_clojure_spec_alpha",
        "@maven//:spyscope_spyscope",
    ],
)
